function output = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SOURCEMETERNO07UREF300MVRH311OHMSFIXED10MAOXYGEN2HZLASER =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  SOURCEMETERNO07UREF300MVRH311OHMSFIXED10MAOXYGEN2HZLASER =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  sourcemeterno07Uref300mVRH311Ohmsfixed10mAoxygen2HzLaser = importfile("C:\Users\jason\OneDrive - UCB-O365\Grad Projects\FIPEX Tests\fipex\data\Igor Tests\220830_source-meter_no07_Uref-300mV_RH-311Ohms_fixed-10mA_oxygen_2Hz-Laser.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Sep-2022 18:27:38

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Repeat", "Point", "CH1Current", "CH1Time"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["CH1Current", "CH1Time"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["CH1Current", "CH1Time"], "ThousandsSeparator", ",");

% Import the data
output = readtable(filename, opts);

end